// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// An assignment allows a project to submit jobs
/// of a certain type using slots from the specified reservation.
public struct Assignment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the resource. E.g.:
  /// `projects/myproject/locations/US/reservations/team1-prod/assignments/123`.
  /// The assignment_id must only contain lower case alphanumeric characters or
  /// dashes and the max length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. The resource which will use the reservation. E.g.
  /// `projects/myproject`, `folders/123`, or `organizations/456`.
  public var assignee: Swift.String = Swift.String()

  /// Optional. Which type of jobs will use the reservation.
  public var jobType: Assignment.JobType = Assignment.JobType()

  /// Output only. State of the assignment.
  public var state: Assignment.State = Assignment.State()

  /// Optional. Deprecated: "Gemini in BigQuery" is now available by
  /// default for all BigQuery editions and should not be explicitly set.
  /// Controls if "Gemini in BigQuery"
  /// (https://cloud.google.com/gemini/docs/bigquery/overview) features should be
  /// enabled for this reservation assignment.
  @available(*, deprecated)
  public var enableGeminiInBigquery: Swift.Bool = Swift.Bool()

  /// Optional. The scheduling policy to use for jobs and queries of this
  /// assignee when running under the associated reservation. The scheduling
  /// policy controls how the reservation's resources are distributed. This
  /// overrides the default scheduling policy specified on the reservation.
  ///
  /// This feature is not yet generally available.
  public var schedulingPolicy: SchedulingPolicy? = nil

  /// Optional. Represents the principal for this assignment. If not empty, jobs
  /// run by this principal utilize the associated reservation. Otherwise, jobs
  /// fall back to using the reservation assigned to the project, folder,
  /// or organization, in that order. If no reservation is assigned at any of
  /// these levels, on-demand capacity is used.
  ///
  /// The supported formats are:
  ///
  /// * `principal://goog/subject/USER_EMAIL_ADDRESS` for users,
  /// * `principal://iam.googleapis.com/projects/-/serviceAccounts/SA_EMAIL_ADDRESS`
  ///   for service accounts,
  /// * `principal://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/subject/SUBJECT_ID`
  ///   for workload identity pool identities.
  /// * The special value `unknown_or_deleted_user` represents principals which
  ///   cannot be read from the user info service, for example, deleted users.
  public var principal: Swift.String = Swift.String()

  /// Optional. Specifies the priority precedence for this assignment. Used to
  /// resolve ambiguity when multiple assignments match a single job. Higher
  /// numerical values represent higher priority (e.g., 20 is higher than 10). If
  /// unspecified, it defaults to 0. Multiple assignments can share the same
  /// precedence, but it is recommended to use unique precedence values for
  /// assignments within the same assignee scope.
  public var `precedence`: Swift.Int64 = Swift.Int64()

  /// Optional. Common Expression Language (CEL) condition that defines the
  /// matching criteria for this assignment.
  /// The condition must resolve to a boolean value.
  /// Supported variables will be added later.
  public var condition: GoogleType.Expr? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Assignment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Assignment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let assignee = CodingKeys(stringValue: "assignee")
    static let jobType = CodingKeys(stringValue: "jobType")
    static let state = CodingKeys(stringValue: "state")
    static let enableGeminiInBigquery = CodingKeys(stringValue: "enableGeminiInBigquery")
    static let schedulingPolicy = CodingKeys(stringValue: "schedulingPolicy")
    static let principal = CodingKeys(stringValue: "principal")
    static let `precedence` = CodingKeys(stringValue: "precedence")
    static let condition = CodingKeys(stringValue: "condition")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "assignee",
      "jobType",
      "state",
      "enableGeminiInBigquery",
      "schedulingPolicy",
      "principal",
      "precedence",
      "condition",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .assignee) {
      self.assignee = value
    }
    if let value = try container.decodeIfPresent(Assignment.JobType.self, forKey: .jobType) {
      self.jobType = value
    }
    if let value = try container.decodeIfPresent(Assignment.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableGeminiInBigquery) {
      self.enableGeminiInBigquery = value
    }
    self.schedulingPolicy = try container.decodeIfPresent(
      SchedulingPolicy.self, forKey: .schedulingPolicy)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .principal) {
      self.principal = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .`precedence`) {
      self.`precedence` = value
    }
    self.condition = try container.decodeIfPresent(GoogleType.Expr.self, forKey: .condition)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.assignee, forKey: .assignee)
    try container.encode(self.jobType, forKey: .jobType)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.enableGeminiInBigquery, forKey: .enableGeminiInBigquery)
    try container.encodeIfPresent(self.schedulingPolicy, forKey: .schedulingPolicy)
    try container.encode(self.principal, forKey: .principal)
    try container.encode(self.`precedence`, forKey: .`precedence`)
    try container.encodeIfPresent(self.condition, forKey: .condition)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of job, which could be specified when using the reservation.
  public enum JobType: Codable, Equatable, Sendable {
    /// Invalid type. Requests with this value will be rejected with
    /// error code `google.rpc.Code.INVALID_ARGUMENT`.
    case unspecified
    /// Pipeline (load/export) jobs from the project will use the reservation.
    case pipeline
    /// Query jobs from the project will use the reservation.
    case query
    /// BigQuery ML jobs that use services external to BigQuery for model
    /// training. These jobs will not utilize idle slots from other reservations.
    case mlExternal
    /// Background jobs that BigQuery runs for the customers in the background.
    case background
    /// Continuous SQL jobs will use this reservation. Reservations with
    /// continuous assignments cannot be mixed with non-continuous assignments.
    case continuous
    /// Finer granularity background jobs for capturing changes in a source
    /// database and streaming them into BigQuery. Reservations with this job
    /// type take priority over a default BACKGROUND reservation assignment (if
    /// it exists).
    case backgroundChangeDataCapture
    /// Finer granularity background jobs for refreshing cached metadata for
    /// BigQuery tables. Reservations with this job type take priority over a
    /// default BACKGROUND reservation assignment (if it exists).
    case backgroundColumnMetadataIndex
    /// Finer granularity background jobs for refreshing search indexes upon
    /// BigQuery table columns. Reservations with this job type
    /// take priority over a default BACKGROUND reservation assignment (if it
    /// exists).
    case backgroundSearchIndexRefresh
    /// Automated materialized view refresh jobs will use the reservation.
    /// Reservations with this job type will take priority over a default QUERY
    /// reservation assignment (if it exists).
    case automaticMaterializedViewRefresh
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pipeline: return 1
      case .query: return 2
      case .mlExternal: return 3
      case .background: return 4
      case .continuous: return 6
      case .backgroundChangeDataCapture: return 7
      case .backgroundColumnMetadataIndex: return 8
      case .backgroundSearchIndexRefresh: return 9
      case .automaticMaterializedViewRefresh: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "JOB_TYPE_UNSPECIFIED"
      case .pipeline: return "PIPELINE"
      case .query: return "QUERY"
      case .mlExternal: return "ML_EXTERNAL"
      case .background: return "BACKGROUND"
      case .continuous: return "CONTINUOUS"
      case .backgroundChangeDataCapture: return "BACKGROUND_CHANGE_DATA_CAPTURE"
      case .backgroundColumnMetadataIndex: return "BACKGROUND_COLUMN_METADATA_INDEX"
      case .backgroundSearchIndexRefresh: return "BACKGROUND_SEARCH_INDEX_REFRESH"
      case .automaticMaterializedViewRefresh: return "AUTOMATIC_MATERIALIZED_VIEW_REFRESH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "JOB_TYPE_UNSPECIFIED": self = .unspecified
      case "PIPELINE": self = .pipeline
      case "QUERY": self = .query
      case "ML_EXTERNAL": self = .mlExternal
      case "BACKGROUND": self = .background
      case "CONTINUOUS": self = .continuous
      case "BACKGROUND_CHANGE_DATA_CAPTURE": self = .backgroundChangeDataCapture
      case "BACKGROUND_COLUMN_METADATA_INDEX": self = .backgroundColumnMetadataIndex
      case "BACKGROUND_SEARCH_INDEX_REFRESH": self = .backgroundSearchIndexRefresh
      case "AUTOMATIC_MATERIALIZED_VIEW_REFRESH": self = .automaticMaterializedViewRefresh
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pipeline
      case 2: self = .query
      case 3: self = .mlExternal
      case 4: self = .background
      case 6: self = .continuous
      case 7: self = .backgroundChangeDataCapture
      case 8: self = .backgroundColumnMetadataIndex
      case 9: self = .backgroundSearchIndexRefresh
      case 10: self = .automaticMaterializedViewRefresh
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("JOB_TYPE_UNSPECIFIED")
      case .pipeline: return try container.encode("PIPELINE")
      case .query: return try container.encode("QUERY")
      case .mlExternal: return try container.encode("ML_EXTERNAL")
      case .background: return try container.encode("BACKGROUND")
      case .continuous: return try container.encode("CONTINUOUS")
      case .backgroundChangeDataCapture:
        return try container.encode("BACKGROUND_CHANGE_DATA_CAPTURE")
      case .backgroundColumnMetadataIndex:
        return try container.encode("BACKGROUND_COLUMN_METADATA_INDEX")
      case .backgroundSearchIndexRefresh:
        return try container.encode("BACKGROUND_SEARCH_INDEX_REFRESH")
      case .automaticMaterializedViewRefresh:
        return try container.encode("AUTOMATIC_MATERIALIZED_VIEW_REFRESH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Assignment will remain in PENDING state if no active capacity commitment is
  /// present. It will become ACTIVE when some capacity commitment becomes
  /// active.
  public enum State: Codable, Equatable, Sendable {
    /// Invalid state value.
    case unspecified
    /// Queries from assignee will be executed as on-demand, if related
    /// assignment is pending.
    case pending
    /// Assignment is ready.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .active: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .active: return try container.encode("ACTIVE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.Assignment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
