// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// Capacity commitment is a way to purchase compute capacity for BigQuery jobs
/// (in the form of slots) with some committed period of usage. Annual
/// commitments renew by default. Commitments can be removed after their
/// commitment end time passes.
///
/// In order to remove annual commitment, its plan needs to be changed
/// to monthly or flex first.
///
/// A capacity commitment resource exists as a child resource of the admin
/// project.
public struct CapacityCommitment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the capacity commitment, e.g.,
  /// `projects/myproject/locations/US/capacityCommitments/123`
  /// The commitment_id must only contain lower case alphanumeric characters or
  /// dashes. It must start with a letter and must not end
  /// with a dash. Its maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. Number of slots in this commitment.
  public var slotCount: Swift.Int64 = Swift.Int64()

  /// Optional. Capacity commitment commitment plan.
  public var plan: CapacityCommitment.CommitmentPlan = CapacityCommitment.CommitmentPlan()

  /// Output only. State of the commitment.
  public var state: CapacityCommitment.State = CapacityCommitment.State()

  /// Output only. The start of the current commitment period. It is applicable
  /// only for ACTIVE capacity commitments. Note after the commitment is renewed,
  /// commitment_start_time won't be changed. It refers to the start time of the
  /// original commitment.
  public var commitmentStartTime: GoogleWKT.Timestamp? = nil

  /// Output only. The end of the current commitment period. It is applicable
  /// only for ACTIVE capacity commitments. Note after renewal,
  /// commitment_end_time is the time the renewed commitment expires. So itwould
  /// be at a time after commitment_start_time + committed period, because we
  /// don't change commitment_start_time ,
  public var commitmentEndTime: GoogleWKT.Timestamp? = nil

  /// Output only. For FAILED commitment plan, provides the reason of failure.
  public var failureStatus: GoogleRpc.Status? = nil

  /// Optional. The plan this capacity commitment is converted to after
  /// commitment_end_time passes. Once the plan is changed, committed period is
  /// extended according to commitment plan. Only applicable for ANNUAL and TRIAL
  /// commitments.
  public var renewalPlan: CapacityCommitment.CommitmentPlan = CapacityCommitment.CommitmentPlan()

  /// Applicable only for commitments located within one of the BigQuery
  /// multi-regions (US or EU).
  ///
  /// If set to true, this commitment is placed in the organization's
  /// secondary region which is designated for disaster recovery purposes.
  /// If false, this commitment is placed in the organization's default region.
  ///
  /// NOTE: this is a preview feature. Project must be allow-listed in order to
  /// set this field.
  @available(*, deprecated)
  public var multiRegionAuxiliary: Swift.Bool = Swift.Bool()

  /// Optional. Edition of the capacity commitment.
  public var edition: Edition = Edition()

  /// Output only. If true, the commitment is a flat-rate commitment, otherwise,
  /// it's an edition commitment.
  public var isFlatRate: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CapacityCommitment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CapacityCommitment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let slotCount = CodingKeys(stringValue: "slotCount")
    static let plan = CodingKeys(stringValue: "plan")
    static let state = CodingKeys(stringValue: "state")
    static let commitmentStartTime = CodingKeys(stringValue: "commitmentStartTime")
    static let commitmentEndTime = CodingKeys(stringValue: "commitmentEndTime")
    static let failureStatus = CodingKeys(stringValue: "failureStatus")
    static let renewalPlan = CodingKeys(stringValue: "renewalPlan")
    static let multiRegionAuxiliary = CodingKeys(stringValue: "multiRegionAuxiliary")
    static let edition = CodingKeys(stringValue: "edition")
    static let isFlatRate = CodingKeys(stringValue: "isFlatRate")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "slotCount",
      "plan",
      "state",
      "commitmentStartTime",
      "commitmentEndTime",
      "failureStatus",
      "renewalPlan",
      "multiRegionAuxiliary",
      "edition",
      "isFlatRate",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .slotCount) {
      self.slotCount = value
    }
    if let value = try container.decodeIfPresent(
      CapacityCommitment.CommitmentPlan.self, forKey: .plan)
    {
      self.plan = value
    }
    if let value = try container.decodeIfPresent(CapacityCommitment.State.self, forKey: .state) {
      self.state = value
    }
    self.commitmentStartTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .commitmentStartTime)
    self.commitmentEndTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .commitmentEndTime)
    self.failureStatus = try container.decodeIfPresent(
      GoogleRpc.Status.self, forKey: .failureStatus)
    if let value = try container.decodeIfPresent(
      CapacityCommitment.CommitmentPlan.self, forKey: .renewalPlan)
    {
      self.renewalPlan = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .multiRegionAuxiliary) {
      self.multiRegionAuxiliary = value
    }
    if let value = try container.decodeIfPresent(Edition.self, forKey: .edition) {
      self.edition = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isFlatRate) {
      self.isFlatRate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.slotCount, forKey: .slotCount)
    try container.encode(self.plan, forKey: .plan)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.commitmentStartTime, forKey: .commitmentStartTime)
    try container.encodeIfPresent(self.commitmentEndTime, forKey: .commitmentEndTime)
    try container.encodeIfPresent(self.failureStatus, forKey: .failureStatus)
    try container.encode(self.renewalPlan, forKey: .renewalPlan)
    try container.encode(self.multiRegionAuxiliary, forKey: .multiRegionAuxiliary)
    try container.encode(self.edition, forKey: .edition)
    try container.encode(self.isFlatRate, forKey: .isFlatRate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Commitment plan defines the current committed period. Capacity commitment
  /// cannot be deleted during it's committed period.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CommitmentPlan: Codable, Equatable, Sendable {
    /// Invalid plan value. Requests with this value will be rejected with
    /// error code `google.rpc.Code.INVALID_ARGUMENT`.
    case unspecified
    /// Monthly commitments have a committed period of 30 days after becoming
    /// ACTIVE. After that, they are not in a committed period anymore and can be
    /// removed any time.
    case monthly
    /// Deprecated: Flex commitments are deprecated. Please use Edition-based
    /// capacity commitments.
    /// Flex commitments have committed period of 1 minute after becoming ACTIVE.
    /// After that, they are not in a committed period anymore and can be removed
    /// any time.
    @available(*, deprecated)
    case flex
    /// Annual commitments have a committed period of 365 days after becoming
    /// ACTIVE. After that they are converted to a new commitment based on the
    /// renewal_plan.
    case annual
    /// Trial commitments have a committed period of 182 days after becoming
    /// ACTIVE. After that, they are converted to a new commitment based on the
    /// `renewal_plan`. Default `renewal_plan` for Trial commitment is Flex so
    /// that it can be deleted right after committed period ends.
    @available(*, deprecated)
    case trial
    /// Should only be used for `renewal_plan` and is only meaningful if
    /// edition is specified to values other than EDITION_UNSPECIFIED. Otherwise
    /// CreateCapacityCommitmentRequest or UpdateCapacityCommitmentRequest will
    /// be rejected with error code `google.rpc.Code.INVALID_ARGUMENT`. If the
    /// renewal_plan is NONE, capacity commitment will be removed at the end of
    /// its commitment period.
    case `none`
    /// Same as FLEX, should only be used if flat-rate commitments are still
    /// available.
    @available(*, deprecated)
    case flexFlatRate
    /// Same as MONTHLY, should only be used if flat-rate commitments are still
    /// available.
    @available(*, deprecated)
    case monthlyFlatRate
    /// Same as ANNUAL, should only be used if flat-rate commitments are still
    /// available.
    @available(*, deprecated)
    case annualFlatRate
    /// 3-year commitments have a committed period of 1095(3 * 365) days after
    /// becoming ACTIVE. After that they are converted to a new commitment based
    /// on the renewal_plan.
    case threeYear
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .monthly: return 2
      case .flex: return 3
      case .annual: return 4
      case .trial: return 5
      case .`none`: return 6
      case .flexFlatRate: return 7
      case .monthlyFlatRate: return 8
      case .annualFlatRate: return 9
      case .threeYear: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMMITMENT_PLAN_UNSPECIFIED"
      case .monthly: return "MONTHLY"
      case .flex: return "FLEX"
      case .annual: return "ANNUAL"
      case .trial: return "TRIAL"
      case .`none`: return "NONE"
      case .flexFlatRate: return "FLEX_FLAT_RATE"
      case .monthlyFlatRate: return "MONTHLY_FLAT_RATE"
      case .annualFlatRate: return "ANNUAL_FLAT_RATE"
      case .threeYear: return "THREE_YEAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommitmentPlan/unknownStringValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMMITMENT_PLAN_UNSPECIFIED": self = .unspecified
      case "FLEX": self = .flex
      case "FLEX_FLAT_RATE": self = .flexFlatRate
      case "TRIAL": self = .trial
      case "MONTHLY": self = .monthly
      case "MONTHLY_FLAT_RATE": self = .monthlyFlatRate
      case "ANNUAL": self = .annual
      case "ANNUAL_FLAT_RATE": self = .annualFlatRate
      case "THREE_YEAR": self = .threeYear
      case "NONE": self = .`none`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommitmentPlan/unknownIntValue(_:)).
    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .monthly
      case 3: self = .flex
      case 4: self = .annual
      case 5: self = .trial
      case 6: self = .`none`
      case 7: self = .flexFlatRate
      case 8: self = .monthlyFlatRate
      case 9: self = .annualFlatRate
      case 10: self = .threeYear
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("COMMITMENT_PLAN_UNSPECIFIED")
      case .monthly: return try container.encode("MONTHLY")
      case .flex: return try container.encode("FLEX")
      case .annual: return try container.encode("ANNUAL")
      case .trial: return try container.encode("TRIAL")
      case .`none`: return try container.encode("NONE")
      case .flexFlatRate: return try container.encode("FLEX_FLAT_RATE")
      case .monthlyFlatRate: return try container.encode("MONTHLY_FLAT_RATE")
      case .annualFlatRate: return try container.encode("ANNUAL_FLAT_RATE")
      case .threeYear: return try container.encode("THREE_YEAR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Capacity commitment can either become ACTIVE right away or transition
  /// from PENDING to ACTIVE or FAILED.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Invalid state value.
    case unspecified
    /// Capacity commitment is pending provisioning. Pending capacity commitment
    /// does not contribute to the project's slot_capacity.
    case pending
    /// Once slots are provisioned, capacity commitment becomes active.
    /// slot_count is added to the project's slot_capacity.
    case active
    /// Capacity commitment is failed to be activated by the backend.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .active: return 2
      case .failed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .active
      case 3: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .active: return try container.encode("ACTIVE")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.CapacityCommitment"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
