// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request for
/// [ReservationService.CreateReservationGroup][google.cloud.bigquery.reservation.v1.ReservationService.CreateReservationGroup].
///
/// [google.cloud.bigquery.reservation.v1.ReservationService.CreateReservationGroup]: <doc:ReservationServiceClient/createReservationGroup(request:options:)>
public struct CreateReservationGroupRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Project, location. E.g.,
  /// `projects/myproject/locations/US`
  public var parent: Swift.String = Swift.String()

  /// Required. The reservation group ID. It must only contain lower case
  /// alphanumeric characters or dashes. It must start with a letter and must not
  /// end with a dash. Its maximum length is 64 characters.
  public var reservationGroupId: Swift.String = Swift.String()

  /// Required. New Reservation Group to create.
  public var reservationGroup: ReservationGroup? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateReservationGroupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateReservationGroupRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let reservationGroupId = CodingKeys(stringValue: "reservationGroupId")
    static let reservationGroup = CodingKeys(stringValue: "reservationGroup")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "reservationGroupId",
      "reservationGroup",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservationGroupId) {
      self.reservationGroupId = value
    }
    self.reservationGroup = try container.decodeIfPresent(
      ReservationGroup.self, forKey: .reservationGroup)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.reservationGroupId, forKey: .reservationGroupId)
    try container.encodeIfPresent(self.reservationGroup, forKey: .reservationGroup)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.CreateReservationGroupRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
