// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// This API allows users to manage their BigQuery reservations.
///
/// A reservation provides computational resource guarantees, in the form of
/// [slots](https://cloud.google.com/bigquery/docs/slots), to users. A slot is a
/// unit of computational power in BigQuery, and serves as the basic unit of
/// parallelism. In a scan of a multi-partitioned table, a single slot operates
/// on a single partition of the table. A reservation resource exists as a child
/// resource of the admin project and location, e.g.:
///   `projects/myproject/locations/US/reservations/reservationName`.
///
/// A capacity commitment is a way to purchase compute capacity for BigQuery jobs
/// (in the form of slots) with some committed period of usage. A capacity
/// commitment resource exists as a child resource of the admin project and
/// location, e.g.:
///   `projects/myproject/locations/US/capacityCommitments/id`.
///
/// @Snippet(path: "ReservationServiceQuickstart")
public final class ReservationServiceClient: Clients.ReservationServiceProtocol, Sendable {
  let inner: any Clients.ReservationServiceStub

  /// Creates a new `ReservationServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ReservationServiceStub = try Clients.ReservationServiceTransport(options)
    inner = Clients.ReservationServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ReservationServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new reservation resource.
  ///
  /// @Snippet(path: "ReservationService_CreateReservation")
  public func createReservation(
    request: CreateReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    try await self.inner.createReservation(request: request, options: options)
  }

  /// Lists all the reservations for the project in the specified location.
  ///
  /// @Snippet(path: "ReservationService_ListReservations")
  public func listReservations(
    request: ListReservationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse {
    try await self.inner.listReservations(request: request, options: options)
  }

  /// Returns information about the reservation.
  ///
  /// @Snippet(path: "ReservationService_GetReservation")
  public func getReservation(
    request: GetReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    try await self.inner.getReservation(request: request, options: options)
  }

  /// Deletes a reservation.
  /// Returns `google.rpc.Code.FAILED_PRECONDITION` when reservation has
  /// assignments.
  ///
  /// @Snippet(path: "ReservationService_DeleteReservation")
  public func deleteReservation(
    request: DeleteReservationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteReservation(request: request, options: options)
  }

  /// Updates an existing reservation resource.
  ///
  /// @Snippet(path: "ReservationService_UpdateReservation")
  public func updateReservation(
    request: UpdateReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    try await self.inner.updateReservation(request: request, options: options)
  }

  /// Fail over a reservation to the secondary location. The operation should be
  /// done in the current secondary location, which will be promoted to the
  /// new primary location for the reservation.
  /// Attempting to failover a reservation in the current primary location will
  /// fail with the error code `google.rpc.Code.FAILED_PRECONDITION`.
  ///
  /// @Snippet(path: "ReservationService_FailoverReservation")
  public func failoverReservation(
    request: FailoverReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    try await self.inner.failoverReservation(request: request, options: options)
  }

  /// Creates a new capacity commitment resource.
  ///
  /// @Snippet(path: "ReservationService_CreateCapacityCommitment")
  public func createCapacityCommitment(
    request: CreateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    try await self.inner.createCapacityCommitment(request: request, options: options)
  }

  /// Lists all the capacity commitments for the admin project.
  ///
  /// @Snippet(path: "ReservationService_ListCapacityCommitments")
  public func listCapacityCommitments(
    request: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse {
    try await self.inner.listCapacityCommitments(request: request, options: options)
  }

  /// Returns information about the capacity commitment.
  ///
  /// @Snippet(path: "ReservationService_GetCapacityCommitment")
  public func getCapacityCommitment(
    request: GetCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    try await self.inner.getCapacityCommitment(request: request, options: options)
  }

  /// Deletes a capacity commitment. Attempting to delete capacity commitment
  /// before its commitment_end_time will fail with the error code
  /// `google.rpc.Code.FAILED_PRECONDITION`.
  ///
  /// @Snippet(path: "ReservationService_DeleteCapacityCommitment")
  public func deleteCapacityCommitment(
    request: DeleteCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteCapacityCommitment(request: request, options: options)
  }

  /// Updates an existing capacity commitment.
  ///
  /// Only `plan` and `renewal_plan` fields can be updated.
  ///
  /// Plan can only be changed to a plan of a longer commitment period.
  /// Attempting to change to a plan with shorter commitment period will fail
  /// with the error code `google.rpc.Code.FAILED_PRECONDITION`.
  ///
  /// @Snippet(path: "ReservationService_UpdateCapacityCommitment")
  public func updateCapacityCommitment(
    request: UpdateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    try await self.inner.updateCapacityCommitment(request: request, options: options)
  }

  /// Splits capacity commitment to two commitments of the same plan and
  /// `commitment_end_time`.
  ///
  /// A common use case is to enable downgrading commitments.
  ///
  /// For example, in order to downgrade from 10000 slots to 8000, you might
  /// split a 10000 capacity commitment into commitments of 2000 and 8000. Then,
  /// you delete the first one after the commitment end time passes.
  ///
  /// @Snippet(path: "ReservationService_SplitCapacityCommitment")
  public func splitCapacityCommitment(
    request: SplitCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse {
    try await self.inner.splitCapacityCommitment(request: request, options: options)
  }

  /// Merges capacity commitments of the same plan into a single commitment.
  ///
  /// The resulting capacity commitment has the greater commitment_end_time
  /// out of the to-be-merged capacity commitments.
  ///
  /// Attempting to merge capacity commitments of different plan will fail
  /// with the error code `google.rpc.Code.FAILED_PRECONDITION`.
  ///
  /// @Snippet(path: "ReservationService_MergeCapacityCommitments")
  public func mergeCapacityCommitments(
    request: MergeCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    try await self.inner.mergeCapacityCommitments(request: request, options: options)
  }

  /// Creates an assignment object which allows the given project to submit jobs
  /// of a certain type using slots from the specified reservation.
  ///
  /// Currently a
  /// resource (project, folder, organization) can only have one assignment per
  /// each (job_type, location) combination, and that reservation will be used
  /// for all jobs of the matching type.
  ///
  /// Different assignments can be created on different levels of the
  /// projects, folders or organization hierarchy.  During query execution,
  /// the assignment is looked up at the project, folder and organization levels
  /// in that order. The first assignment found is applied to the query.
  ///
  /// When creating assignments, it does not matter if other assignments exist at
  /// higher levels.
  ///
  /// Example:
  ///
  /// * The organization `organizationA` contains two projects, `project1`
  ///   and `project2`.
  /// * Assignments for all three entities (`organizationA`, `project1`, and
  ///   `project2`) could all be created and mapped to the same or different
  ///   reservations.
  ///
  /// "None" assignments represent an absence of the assignment. Projects
  /// assigned to None use on-demand pricing. To create a "None" assignment, use
  /// "none" as a reservation_id in the parent. Example parent:
  /// `projects/myproject/locations/US/reservations/none`.
  ///
  /// Returns `google.rpc.Code.PERMISSION_DENIED` if user does not have
  /// 'bigquery.admin' permissions on the project using the reservation
  /// and the project that owns this reservation.
  ///
  /// Returns `google.rpc.Code.INVALID_ARGUMENT` when location of the assignment
  /// does not match location of the reservation.
  ///
  /// @Snippet(path: "ReservationService_CreateAssignment")
  public func createAssignment(
    request: CreateAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    try await self.inner.createAssignment(request: request, options: options)
  }

  /// Lists assignments.
  ///
  /// Only explicitly created assignments will be returned.
  ///
  /// Example:
  ///
  /// * Organization `organizationA` contains two projects, `project1` and
  ///   `project2`.
  /// * Reservation `res1` exists and was created previously.
  /// * CreateAssignment was used previously to define the following
  ///   associations between entities and reservations: `<organizationA, res1>`
  ///   and `<project1, res1>`
  ///
  /// In this example, ListAssignments will just return the above two assignments
  /// for reservation `res1`, and no expansion/merge will happen.
  ///
  /// The wildcard "-" can be used for
  /// reservations in the request. In that case all assignments belongs to the
  /// specified project and location will be listed.
  ///
  /// **Note** "-" cannot be used for projects nor locations.
  ///
  /// @Snippet(path: "ReservationService_ListAssignments")
  public func listAssignments(
    request: ListAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse {
    try await self.inner.listAssignments(request: request, options: options)
  }

  /// Deletes a assignment. No expansion will happen.
  ///
  /// Example:
  ///
  /// * Organization `organizationA` contains two projects, `project1` and
  ///   `project2`.
  /// * Reservation `res1` exists and was created previously.
  /// * CreateAssignment was used previously to define the following
  ///   associations between entities and reservations: `<organizationA, res1>`
  ///   and `<project1, res1>`
  ///
  /// In this example, deletion of the `<organizationA, res1>` assignment won't
  /// affect the other assignment `<project1, res1>`. After said deletion,
  /// queries from `project1` will still use `res1` while queries from
  /// `project2` will switch to use on-demand mode.
  ///
  /// @Snippet(path: "ReservationService_DeleteAssignment")
  public func deleteAssignment(
    request: DeleteAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAssignment(request: request, options: options)
  }

  /// Deprecated: Looks up assignments for a specified resource for a particular
  /// region. If the request is about a project:
  ///
  /// 1. Assignments created on the project will be returned if they exist.
  /// 2. Otherwise assignments created on the closest ancestor will be
  ///    returned.
  /// 3. Assignments for different JobTypes will all be returned.
  ///
  /// The same logic applies if the request is about a folder.
  ///
  /// If the request is about an organization, then assignments created on the
  /// organization will be returned (organization doesn't have ancestors).
  ///
  /// Comparing to ListAssignments, there are some behavior
  /// differences:
  ///
  /// 1. permission on the assignee will be verified in this API.
  /// 2. Hierarchy lookup (project->folder->organization) happens in this API.
  /// 3. Parent here is `projects/*/locations/*`, instead of
  ///    `projects/*/locations/*reservations/*`.
  ///
  /// **Note** "-" cannot be used for projects
  /// nor locations.
  ///
  /// @Snippet(path: "ReservationService_SearchAssignments")
  @available(*, deprecated)
  public func searchAssignments(
    request: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse {
    try await self.inner.searchAssignments(request: request, options: options)
  }

  /// Looks up assignments for a specified resource for a particular region.
  /// If the request is about a project:
  ///
  /// 1. Assignments created on the project will be returned if they exist.
  /// 2. Otherwise assignments created on the closest ancestor will be
  ///    returned.
  /// 3. Assignments for different JobTypes will all be returned.
  ///
  /// The same logic applies if the request is about a folder.
  ///
  /// If the request is about an organization, then assignments created on the
  /// organization will be returned (organization doesn't have ancestors).
  ///
  /// Comparing to ListAssignments, there are some behavior
  /// differences:
  ///
  /// 1. permission on the assignee will be verified in this API.
  /// 2. Hierarchy lookup (project->folder->organization) happens in this API.
  /// 3. Parent here is `projects/*/locations/*`, instead of
  ///    `projects/*/locations/*reservations/*`.
  ///
  /// @Snippet(path: "ReservationService_SearchAllAssignments")
  public func searchAllAssignments(
    request: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse {
    try await self.inner.searchAllAssignments(request: request, options: options)
  }

  /// Moves an assignment under a new reservation.
  ///
  /// This differs from removing an existing assignment and recreating a new one
  /// by providing a transactional change that ensures an assignee always has an
  /// associated reservation.
  ///
  /// @Snippet(path: "ReservationService_MoveAssignment")
  public func moveAssignment(
    request: MoveAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    try await self.inner.moveAssignment(request: request, options: options)
  }

  /// Updates an existing assignment.
  ///
  /// Only the `priority` field can be updated.
  ///
  /// @Snippet(path: "ReservationService_UpdateAssignment")
  public func updateAssignment(
    request: UpdateAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    try await self.inner.updateAssignment(request: request, options: options)
  }

  /// Retrieves a BI reservation.
  ///
  /// @Snippet(path: "ReservationService_GetBiReservation")
  public func getBiReservation(
    request: GetBiReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    try await self.inner.getBiReservation(request: request, options: options)
  }

  /// Updates a BI reservation.
  ///
  /// Only fields specified in the `field_mask` are updated.
  ///
  /// A singleton BI reservation always exists with default size 0.
  /// In order to reserve BI capacity it needs to be updated to an amount
  /// greater than 0. In order to release BI capacity reservation size
  /// must be set to 0.
  ///
  /// @Snippet(path: "ReservationService_UpdateBiReservation")
  public func updateBiReservation(
    request: UpdateBiReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    try await self.inner.updateBiReservation(request: request, options: options)
  }

  /// Gets the access control policy for a resource.
  /// May return:
  ///
  /// * A`NOT_FOUND` error if the resource doesn't exist or you don't have the
  ///   permission to view it.
  /// * An empty policy if the resource exists but doesn't have a set policy.
  ///
  /// Supported resources are:
  /// - Reservations
  /// - ReservationAssignments
  ///
  /// To call this method, you must have the following Google IAM permissions:
  ///
  /// - `bigqueryreservation.reservations.getIamPolicy` to get policies on
  /// reservations.
  ///
  /// @Snippet(path: "ReservationService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets an access control policy for a resource. Replaces any existing
  /// policy.
  ///
  /// Supported resources are:
  /// - Reservations
  ///
  /// To call this method, you must have the following Google IAM permissions:
  ///
  /// - `bigqueryreservation.reservations.setIamPolicy` to set policies on
  /// reservations.
  ///
  /// @Snippet(path: "ReservationService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets your permissions on a resource. Returns an empty set of permissions if
  /// the resource doesn't exist.
  ///
  /// Supported resources are:
  /// - Reservations
  ///
  /// No Google IAM permissions are required to call this method.
  ///
  /// @Snippet(path: "ReservationService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Creates a new reservation group.
  ///
  /// @Snippet(path: "ReservationService_CreateReservationGroup")
  public func createReservationGroup(
    request: CreateReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    try await self.inner.createReservationGroup(request: request, options: options)
  }

  /// Returns information about the reservation group.
  ///
  /// @Snippet(path: "ReservationService_GetReservationGroup")
  public func getReservationGroup(
    request: GetReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    try await self.inner.getReservationGroup(request: request, options: options)
  }

  /// Deletes a reservation.
  /// Returns `google.rpc.Code.FAILED_PRECONDITION` when reservation has
  /// assignments.
  ///
  /// @Snippet(path: "ReservationService_DeleteReservationGroup")
  public func deleteReservationGroup(
    request: DeleteReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteReservationGroup(request: request, options: options)
  }

  /// Lists all the reservation groups for the project in the specified location.
  ///
  /// @Snippet(path: "ReservationService_ListReservationGroups")
  public func listReservationGroups(
    request: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse {
    try await self.inner.listReservationGroups(request: request, options: options)
  }

  /// Updates an existing reservation group resource.
  ///
  /// @Snippet(path: "ReservationService_UpdateReservationGroup")
  public func updateReservationGroup(
    request: UpdateReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    try await self.inner.updateReservationGroup(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ReservationServiceClient`.
  ///
  /// To mock `ReservationServiceClient` change your functions to receive
  /// `some ReservationServiceProtocol` or `any ReservationServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ReservationServiceProtocol: Sendable {
    /// See `ReservationServiceClient.createReservation`.
    func createReservation(
      request: CreateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    /// See `ReservationServiceClient.listReservations`.
    func listReservations(
      request: ListReservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse

    /// See `ReservationServiceClient.getReservation`.
    func getReservation(
      request: GetReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    /// See `ReservationServiceClient.deleteReservation`.
    func deleteReservation(
      request: DeleteReservationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ReservationServiceClient.updateReservation`.
    func updateReservation(
      request: UpdateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    /// See `ReservationServiceClient.failoverReservation`.
    func failoverReservation(
      request: FailoverReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    /// See `ReservationServiceClient.createCapacityCommitment`.
    func createCapacityCommitment(
      request: CreateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    /// See `ReservationServiceClient.listCapacityCommitments`.
    func listCapacityCommitments(
      request: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse

    /// See `ReservationServiceClient.getCapacityCommitment`.
    func getCapacityCommitment(
      request: GetCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    /// See `ReservationServiceClient.deleteCapacityCommitment`.
    func deleteCapacityCommitment(
      request: DeleteCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ReservationServiceClient.updateCapacityCommitment`.
    func updateCapacityCommitment(
      request: UpdateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    /// See `ReservationServiceClient.splitCapacityCommitment`.
    func splitCapacityCommitment(
      request: SplitCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse

    /// See `ReservationServiceClient.mergeCapacityCommitments`.
    func mergeCapacityCommitments(
      request: MergeCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    /// See `ReservationServiceClient.createAssignment`.
    func createAssignment(
      request: CreateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    /// See `ReservationServiceClient.listAssignments`.
    func listAssignments(
      request: ListAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse

    /// See `ReservationServiceClient.deleteAssignment`.
    func deleteAssignment(
      request: DeleteAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ReservationServiceClient.searchAssignments`.
    @available(*, deprecated)
    func searchAssignments(
      request: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse

    /// See `ReservationServiceClient.searchAllAssignments`.
    func searchAllAssignments(
      request: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse

    /// See `ReservationServiceClient.moveAssignment`.
    func moveAssignment(
      request: MoveAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    /// See `ReservationServiceClient.updateAssignment`.
    func updateAssignment(
      request: UpdateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    /// See `ReservationServiceClient.getBiReservation`.
    func getBiReservation(
      request: GetBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation

    /// See `ReservationServiceClient.updateBiReservation`.
    func updateBiReservation(
      request: UpdateBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation

    /// See `ReservationServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ReservationServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ReservationServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ReservationServiceClient.createReservationGroup`.
    func createReservationGroup(
      request: CreateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup

    /// See `ReservationServiceClient.getReservationGroup`.
    func getReservationGroup(
      request: GetReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup

    /// See `ReservationServiceClient.deleteReservationGroup`.
    func deleteReservationGroup(
      request: DeleteReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ReservationServiceClient.listReservationGroups`.
    func listReservationGroups(
      request: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse

    /// See `ReservationServiceClient.updateReservationGroup`.
    func updateReservationGroup(
      request: UpdateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup
  }
}

// Default implementations
extension Clients.ReservationServiceProtocol {
  public func createReservation(request: CreateReservationRequest) async throws
    -> GoogleBigQueryReservationV1.Reservation
  {
    try await self.createReservation(request: request, options: .init())
  }

  public func createReservation(
    request: CreateReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createReservation(
    parent: Swift.String,
    reservation: Reservation?,
    reservationId: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    let request = CreateReservationRequest().with {
      $0.parent = parent
      $0.reservation = reservation
      $0.reservationId = reservationId
    }
    return try await self.createReservation(request: request)
  }

  public func listReservations(request: ListReservationsRequest) async throws
    -> GoogleBigQueryReservationV1.ListReservationsResponse
  {
    try await self.listReservations(request: request, options: .init())
  }

  public func listReservations(
    request: ListReservationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReservations(
    byItem: ListReservationsRequest
  ) -> any AsyncSequence<Reservation, Swift.Error> {
    self.listReservations(byItem: byItem, options: .init())
  }

  /// Lists all the reservations for the project in the specified location.
  ///
  /// @Snippet(path: "ReservationService_ListReservations")
  public func listReservations(
    byItem: ListReservationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Reservation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listReservations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReservations(
    parent: Swift.String,
  ) -> any AsyncSequence<Reservation, Swift.Error> {
    let request = ListReservationsRequest().with {
      $0.parent = parent
    }
    return self.listReservations(byItem: request)
  }

  public func getReservation(request: GetReservationRequest) async throws
    -> GoogleBigQueryReservationV1.Reservation
  {
    try await self.getReservation(request: request, options: .init())
  }

  public func getReservation(
    request: GetReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReservation(
    name: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    let request = GetReservationRequest().with {
      $0.name = name
    }
    return try await self.getReservation(request: request)
  }

  public func deleteReservation(request: DeleteReservationRequest) async throws {
    try await self.deleteReservation(request: request, options: .init())
  }

  public func deleteReservation(
    request: DeleteReservationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteReservation(
    name: Swift.String,
  ) async throws {
    let request = DeleteReservationRequest().with {
      $0.name = name
    }
    try await self.deleteReservation(request: request)
  }

  public func updateReservation(request: UpdateReservationRequest) async throws
    -> GoogleBigQueryReservationV1.Reservation
  {
    try await self.updateReservation(request: request, options: .init())
  }

  public func updateReservation(
    request: UpdateReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateReservation(
    reservation: Reservation?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    let request = UpdateReservationRequest().with {
      $0.reservation = reservation
      $0.updateMask = updateMask
    }
    return try await self.updateReservation(request: request)
  }

  public func failoverReservation(request: FailoverReservationRequest) async throws
    -> GoogleBigQueryReservationV1.Reservation
  {
    try await self.failoverReservation(request: request, options: .init())
  }

  public func failoverReservation(
    request: FailoverReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Reservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createCapacityCommitment(request: CreateCapacityCommitmentRequest) async throws
    -> GoogleBigQueryReservationV1.CapacityCommitment
  {
    try await self.createCapacityCommitment(request: request, options: .init())
  }

  public func createCapacityCommitment(
    request: CreateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createCapacityCommitment(
    parent: Swift.String,
    capacityCommitment: CapacityCommitment?,
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    let request = CreateCapacityCommitmentRequest().with {
      $0.parent = parent
      $0.capacityCommitment = capacityCommitment
    }
    return try await self.createCapacityCommitment(request: request)
  }

  public func listCapacityCommitments(request: ListCapacityCommitmentsRequest) async throws
    -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse
  {
    try await self.listCapacityCommitments(request: request, options: .init())
  }

  public func listCapacityCommitments(
    request: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCapacityCommitments(
    byItem: ListCapacityCommitmentsRequest
  ) -> any AsyncSequence<CapacityCommitment, Swift.Error> {
    self.listCapacityCommitments(byItem: byItem, options: .init())
  }

  /// Lists all the capacity commitments for the admin project.
  ///
  /// @Snippet(path: "ReservationService_ListCapacityCommitments")
  public func listCapacityCommitments(
    byItem: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<CapacityCommitment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCapacityCommitments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCapacityCommitments(
    parent: Swift.String,
  ) -> any AsyncSequence<CapacityCommitment, Swift.Error> {
    let request = ListCapacityCommitmentsRequest().with {
      $0.parent = parent
    }
    return self.listCapacityCommitments(byItem: request)
  }

  public func getCapacityCommitment(request: GetCapacityCommitmentRequest) async throws
    -> GoogleBigQueryReservationV1.CapacityCommitment
  {
    try await self.getCapacityCommitment(request: request, options: .init())
  }

  public func getCapacityCommitment(
    request: GetCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCapacityCommitment(
    name: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    let request = GetCapacityCommitmentRequest().with {
      $0.name = name
    }
    return try await self.getCapacityCommitment(request: request)
  }

  public func deleteCapacityCommitment(request: DeleteCapacityCommitmentRequest) async throws {
    try await self.deleteCapacityCommitment(request: request, options: .init())
  }

  public func deleteCapacityCommitment(
    request: DeleteCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteCapacityCommitment(
    name: Swift.String,
  ) async throws {
    let request = DeleteCapacityCommitmentRequest().with {
      $0.name = name
    }
    try await self.deleteCapacityCommitment(request: request)
  }

  public func updateCapacityCommitment(request: UpdateCapacityCommitmentRequest) async throws
    -> GoogleBigQueryReservationV1.CapacityCommitment
  {
    try await self.updateCapacityCommitment(request: request, options: .init())
  }

  public func updateCapacityCommitment(
    request: UpdateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateCapacityCommitment(
    capacityCommitment: CapacityCommitment?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    let request = UpdateCapacityCommitmentRequest().with {
      $0.capacityCommitment = capacityCommitment
      $0.updateMask = updateMask
    }
    return try await self.updateCapacityCommitment(request: request)
  }

  public func splitCapacityCommitment(request: SplitCapacityCommitmentRequest) async throws
    -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse
  {
    try await self.splitCapacityCommitment(request: request, options: .init())
  }

  public func splitCapacityCommitment(
    request: SplitCapacityCommitmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func splitCapacityCommitment(
    name: Swift.String,
    slotCount: Swift.Int64,
  ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse {
    let request = SplitCapacityCommitmentRequest().with {
      $0.name = name
      $0.slotCount = slotCount
    }
    return try await self.splitCapacityCommitment(request: request)
  }

  public func mergeCapacityCommitments(request: MergeCapacityCommitmentsRequest) async throws
    -> GoogleBigQueryReservationV1.CapacityCommitment
  {
    try await self.mergeCapacityCommitments(request: request, options: .init())
  }

  public func mergeCapacityCommitments(
    request: MergeCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func mergeCapacityCommitments(
    parent: Swift.String,
    capacityCommitmentIds: [Swift.String],
  ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
    let request = MergeCapacityCommitmentsRequest().with {
      $0.parent = parent
      $0.capacityCommitmentIds = capacityCommitmentIds
    }
    return try await self.mergeCapacityCommitments(request: request)
  }

  public func createAssignment(request: CreateAssignmentRequest) async throws
    -> GoogleBigQueryReservationV1.Assignment
  {
    try await self.createAssignment(request: request, options: .init())
  }

  public func createAssignment(
    request: CreateAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAssignment(
    parent: Swift.String,
    assignment: Assignment?,
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    let request = CreateAssignmentRequest().with {
      $0.parent = parent
      $0.assignment = assignment
    }
    return try await self.createAssignment(request: request)
  }

  public func listAssignments(request: ListAssignmentsRequest) async throws
    -> GoogleBigQueryReservationV1.ListAssignmentsResponse
  {
    try await self.listAssignments(request: request, options: .init())
  }

  public func listAssignments(
    request: ListAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAssignments(
    byItem: ListAssignmentsRequest
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    self.listAssignments(byItem: byItem, options: .init())
  }

  /// Lists assignments.
  ///
  /// Only explicitly created assignments will be returned.
  ///
  /// Example:
  ///
  /// * Organization `organizationA` contains two projects, `project1` and
  ///   `project2`.
  /// * Reservation `res1` exists and was created previously.
  /// * CreateAssignment was used previously to define the following
  ///   associations between entities and reservations: `<organizationA, res1>`
  ///   and `<project1, res1>`
  ///
  /// In this example, ListAssignments will just return the above two assignments
  /// for reservation `res1`, and no expansion/merge will happen.
  ///
  /// The wildcard "-" can be used for
  /// reservations in the request. In that case all assignments belongs to the
  /// specified project and location will be listed.
  ///
  /// **Note** "-" cannot be used for projects nor locations.
  ///
  /// @Snippet(path: "ReservationService_ListAssignments")
  public func listAssignments(
    byItem: ListAssignmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAssignments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAssignments(
    parent: Swift.String,
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let request = ListAssignmentsRequest().with {
      $0.parent = parent
    }
    return self.listAssignments(byItem: request)
  }

  public func deleteAssignment(request: DeleteAssignmentRequest) async throws {
    try await self.deleteAssignment(request: request, options: .init())
  }

  public func deleteAssignment(
    request: DeleteAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAssignment(
    name: Swift.String,
  ) async throws {
    let request = DeleteAssignmentRequest().with {
      $0.name = name
    }
    try await self.deleteAssignment(request: request)
  }

  @available(*, deprecated)
  public func searchAssignments(request: SearchAssignmentsRequest) async throws
    -> GoogleBigQueryReservationV1.SearchAssignmentsResponse
  {
    try await self.searchAssignments(request: request, options: .init())
  }

  @available(*, deprecated)
  public func searchAssignments(
    request: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func searchAssignments(
    byItem: SearchAssignmentsRequest
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    self.searchAssignments(byItem: byItem, options: .init())
  }

  /// Deprecated: Looks up assignments for a specified resource for a particular
  /// region. If the request is about a project:
  ///
  /// 1. Assignments created on the project will be returned if they exist.
  /// 2. Otherwise assignments created on the closest ancestor will be
  ///    returned.
  /// 3. Assignments for different JobTypes will all be returned.
  ///
  /// The same logic applies if the request is about a folder.
  ///
  /// If the request is about an organization, then assignments created on the
  /// organization will be returned (organization doesn't have ancestors).
  ///
  /// Comparing to ListAssignments, there are some behavior
  /// differences:
  ///
  /// 1. permission on the assignee will be verified in this API.
  /// 2. Hierarchy lookup (project->folder->organization) happens in this API.
  /// 3. Parent here is `projects/*/locations/*`, instead of
  ///    `projects/*/locations/*reservations/*`.
  ///
  /// **Note** "-" cannot be used for projects
  /// nor locations.
  ///
  /// @Snippet(path: "ReservationService_SearchAssignments")
  @available(*, deprecated)
  public func searchAssignments(
    byItem: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchAssignments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func searchAssignments(
    parent: Swift.String,
    query: Swift.String,
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let request = SearchAssignmentsRequest().with {
      $0.parent = parent
      $0.query = query
    }
    return self.searchAssignments(byItem: request)
  }

  public func searchAllAssignments(request: SearchAllAssignmentsRequest) async throws
    -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse
  {
    try await self.searchAllAssignments(request: request, options: .init())
  }

  public func searchAllAssignments(
    request: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchAllAssignments(
    byItem: SearchAllAssignmentsRequest
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    self.searchAllAssignments(byItem: byItem, options: .init())
  }

  /// Looks up assignments for a specified resource for a particular region.
  /// If the request is about a project:
  ///
  /// 1. Assignments created on the project will be returned if they exist.
  /// 2. Otherwise assignments created on the closest ancestor will be
  ///    returned.
  /// 3. Assignments for different JobTypes will all be returned.
  ///
  /// The same logic applies if the request is about a folder.
  ///
  /// If the request is about an organization, then assignments created on the
  /// organization will be returned (organization doesn't have ancestors).
  ///
  /// Comparing to ListAssignments, there are some behavior
  /// differences:
  ///
  /// 1. permission on the assignee will be verified in this API.
  /// 2. Hierarchy lookup (project->folder->organization) happens in this API.
  /// 3. Parent here is `projects/*/locations/*`, instead of
  ///    `projects/*/locations/*reservations/*`.
  ///
  /// @Snippet(path: "ReservationService_SearchAllAssignments")
  public func searchAllAssignments(
    byItem: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.searchAllAssignments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchAllAssignments(
    parent: Swift.String,
    query: Swift.String,
  ) -> any AsyncSequence<Assignment, Swift.Error> {
    let request = SearchAllAssignmentsRequest().with {
      $0.parent = parent
      $0.query = query
    }
    return self.searchAllAssignments(byItem: request)
  }

  public func moveAssignment(request: MoveAssignmentRequest) async throws
    -> GoogleBigQueryReservationV1.Assignment
  {
    try await self.moveAssignment(request: request, options: .init())
  }

  public func moveAssignment(
    request: MoveAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func moveAssignment(
    name: Swift.String,
    destinationId: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    let request = MoveAssignmentRequest().with {
      $0.name = name
      $0.destinationId = destinationId
    }
    return try await self.moveAssignment(request: request)
  }

  public func updateAssignment(request: UpdateAssignmentRequest) async throws
    -> GoogleBigQueryReservationV1.Assignment
  {
    try await self.updateAssignment(request: request, options: .init())
  }

  public func updateAssignment(
    request: UpdateAssignmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAssignment(
    assignment: Assignment?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleBigQueryReservationV1.Assignment {
    let request = UpdateAssignmentRequest().with {
      $0.assignment = assignment
      $0.updateMask = updateMask
    }
    return try await self.updateAssignment(request: request)
  }

  public func getBiReservation(request: GetBiReservationRequest) async throws
    -> GoogleBigQueryReservationV1.BiReservation
  {
    try await self.getBiReservation(request: request, options: .init())
  }

  public func getBiReservation(
    request: GetBiReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBiReservation(
    name: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    let request = GetBiReservationRequest().with {
      $0.name = name
    }
    return try await self.getBiReservation(request: request)
  }

  public func updateBiReservation(request: UpdateBiReservationRequest) async throws
    -> GoogleBigQueryReservationV1.BiReservation
  {
    try await self.updateBiReservation(request: request, options: .init())
  }

  public func updateBiReservation(
    request: UpdateBiReservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateBiReservation(
    biReservation: BiReservation?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleBigQueryReservationV1.BiReservation {
    let request = UpdateBiReservationRequest().with {
      $0.biReservation = biReservation
      $0.updateMask = updateMask
    }
    return try await self.updateBiReservation(request: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createReservationGroup(request: CreateReservationGroupRequest) async throws
    -> GoogleBigQueryReservationV1.ReservationGroup
  {
    try await self.createReservationGroup(request: request, options: .init())
  }

  public func createReservationGroup(
    request: CreateReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReservationGroup(request: GetReservationGroupRequest) async throws
    -> GoogleBigQueryReservationV1.ReservationGroup
  {
    try await self.getReservationGroup(request: request, options: .init())
  }

  public func getReservationGroup(
    request: GetReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReservationGroup(
    name: Swift.String,
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    let request = GetReservationGroupRequest().with {
      $0.name = name
    }
    return try await self.getReservationGroup(request: request)
  }

  public func deleteReservationGroup(request: DeleteReservationGroupRequest) async throws {
    try await self.deleteReservationGroup(request: request, options: .init())
  }

  public func deleteReservationGroup(
    request: DeleteReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteReservationGroup(
    name: Swift.String,
  ) async throws {
    let request = DeleteReservationGroupRequest().with {
      $0.name = name
    }
    try await self.deleteReservationGroup(request: request)
  }

  public func listReservationGroups(request: ListReservationGroupsRequest) async throws
    -> GoogleBigQueryReservationV1.ListReservationGroupsResponse
  {
    try await self.listReservationGroups(request: request, options: .init())
  }

  public func listReservationGroups(
    request: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReservationGroups(
    byItem: ListReservationGroupsRequest
  ) -> any AsyncSequence<ReservationGroup, Swift.Error> {
    self.listReservationGroups(byItem: byItem, options: .init())
  }

  /// Lists all the reservation groups for the project in the specified location.
  ///
  /// @Snippet(path: "ReservationService_ListReservationGroups")
  public func listReservationGroups(
    byItem: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ReservationGroup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleBigQueryReservationV1.ListReservationGroupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listReservationGroups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReservationGroups(
    parent: Swift.String,
  ) -> any AsyncSequence<ReservationGroup, Swift.Error> {
    let request = ListReservationGroupsRequest().with {
      $0.parent = parent
    }
    return self.listReservationGroups(byItem: request)
  }

  public func updateReservationGroup(request: UpdateReservationGroupRequest) async throws
    -> GoogleBigQueryReservationV1.ReservationGroup
  {
    try await self.updateReservationGroup(request: request, options: .init())
  }

  public func updateReservationGroup(
    request: UpdateReservationGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateReservationGroup(
    reservationGroup: ReservationGroup?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
    let request = UpdateReservationGroupRequest().with {
      $0.reservationGroup = reservationGroup
      $0.updateMask = updateMask
    }
    return try await self.updateReservationGroup(request: request)
  }
}
