// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ReservationServiceRetry: ReservationServiceStub {
    let inner: any ReservationServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ReservationServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createReservation(
      request: CreateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.createReservation(request: r, options: o)
        })
    }

    public func listReservations(
      request: ListReservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReservationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListReservationsResponse
          in
          return try await self.inner.listReservations(request: r, options: o)
        })
    }

    public func getReservation(
      request: GetReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.getReservation(request: r, options: o)
        })
    }

    public func deleteReservation(
      request: DeleteReservationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteReservationRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteReservation(request: r, options: o)
        })
    }

    public func updateReservation(
      request: UpdateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.updateReservation(request: r, options: o)
        })
    }

    public func failoverReservation(
      request: FailoverReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FailoverReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.failoverReservation(request: r, options: o)
        })
    }

    public func createCapacityCommitment(
      request: CreateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCapacityCommitmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.createCapacityCommitment(request: r, options: o)
        })
    }

    public func listCapacityCommitments(
      request: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCapacityCommitmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse
          in
          return try await self.inner.listCapacityCommitments(request: r, options: o)
        })
    }

    public func getCapacityCommitment(
      request: GetCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCapacityCommitmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.getCapacityCommitment(request: r, options: o)
        })
    }

    public func deleteCapacityCommitment(
      request: DeleteCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCapacityCommitmentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCapacityCommitment(request: r, options: o)
        })
    }

    public func updateCapacityCommitment(
      request: UpdateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCapacityCommitmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.updateCapacityCommitment(request: r, options: o)
        })
    }

    public func splitCapacityCommitment(
      request: SplitCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SplitCapacityCommitmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse
          in
          return try await self.inner.splitCapacityCommitment(request: r, options: o)
        })
    }

    public func mergeCapacityCommitments(
      request: MergeCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MergeCapacityCommitmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.mergeCapacityCommitments(request: r, options: o)
        })
    }

    public func createAssignment(
      request: CreateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.createAssignment(request: r, options: o)
        })
    }

    public func listAssignments(
      request: ListAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAssignmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListAssignmentsResponse
          in
          return try await self.inner.listAssignments(request: r, options: o)
        })
    }

    public func deleteAssignment(
      request: DeleteAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteAssignmentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAssignment(request: r, options: o)
        })
    }

    public func searchAssignments(
      request: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchAssignmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SearchAssignmentsResponse
          in
          return try await self.inner.searchAssignments(request: r, options: o)
        })
    }

    public func searchAllAssignments(
      request: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchAllAssignmentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse
          in
          return try await self.inner.searchAllAssignments(request: r, options: o)
        })
    }

    public func moveAssignment(
      request: MoveAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MoveAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.moveAssignment(request: r, options: o)
        })
    }

    public func updateAssignment(
      request: UpdateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAssignmentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.updateAssignment(request: r, options: o)
        })
    }

    public func getBiReservation(
      request: GetBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBiReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.BiReservation
          in
          return try await self.inner.getBiReservation(request: r, options: o)
        })
    }

    public func updateBiReservation(
      request: UpdateBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBiReservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.BiReservation
          in
          return try await self.inner.updateBiReservation(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func createReservationGroup(
      request: CreateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateReservationGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.createReservationGroup(request: r, options: o)
        })
    }

    public func getReservationGroup(
      request: GetReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetReservationGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.getReservationGroup(request: r, options: o)
        })
    }

    public func deleteReservationGroup(
      request: DeleteReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteReservationGroupRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteReservationGroup(request: r, options: o)
        })
    }

    public func listReservationGroups(
      request: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReservationGroupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListReservationGroupsResponse
          in
          return try await self.inner.listReservationGroups(request: r, options: o)
        })
    }

    public func updateReservationGroup(
      request: UpdateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateReservationGroupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.updateReservationGroup(request: r, options: o)
        })
    }
  }
}
