// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A reservation group is a container for reservations.
public struct ReservationGroup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the reservation group, e.g.,
  /// `projects/*/locations/*/reservationGroups/team1-prod`.
  /// The reservation_group_id must only contain lower case alphanumeric
  /// characters or dashes. It must start with a letter and must not end with a
  /// dash. Its maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. The parent reservation group of the reservation group.
  /// Format: `projects/*/locations/*/reservationGroups/team1-prod` for non-root
  /// reservation groups, or `projects/*/locations/*` for root reservation
  /// groups.
  public var parentGroup: Swift.String = Swift.String()

  /// Output only. Creation time of the reservation group.
  public var creationTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Last update time of the reservation group via a user
  /// operation. This timestamp is updated only when an update operation
  /// explicitly targets this reservation group directly. It is not updated when
  /// parent or child groups are created, updated, or deleted.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReservationGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReservationGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let parentGroup = CodingKeys(stringValue: "parentGroup")
    static let creationTime = CodingKeys(stringValue: "creationTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "parentGroup",
      "creationTime",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentGroup) {
      self.parentGroup = value
    }
    self.creationTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .creationTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parentGroup, forKey: .parentGroup)
    try container.encodeIfPresent(self.creationTime, forKey: .creationTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.ReservationGroup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
