// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// A reservation is a mechanism used to guarantee slots to users.
public struct Reservation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the reservation, e.g.,
  /// `projects/*/locations/*/reservations/team1-prod`.
  /// The reservation_id must only contain lower case alphanumeric characters or
  /// dashes. It must start with a letter and must not end with a dash. Its
  /// maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. Baseline slots available to this reservation. A slot is a unit of
  /// computational power in BigQuery, and serves as the unit of parallelism.
  ///
  /// Queries using this reservation might use more slots during runtime if
  /// ignore_idle_slots is set to false, or autoscaling is enabled.
  ///
  /// The total slot_capacity of the reservation and its siblings
  /// may exceed the total slot_count of capacity commitments. In that case, the
  /// exceeding slots will be charged with the autoscale SKU. You can increase
  /// the number of baseline slots in a reservation every few minutes. If you
  /// want to decrease your baseline slots, you are limited to once an hour if
  /// you have recently changed your baseline slot capacity and your baseline
  /// slots exceed your committed slots. Otherwise, you can decrease your
  /// baseline slots every few minutes.
  public var slotCapacity: Swift.Int64 = Swift.Int64()

  /// Optional. If false, any query or pipeline job using this reservation will
  /// use idle slots from other reservations within the same admin project. If
  /// true, a query or pipeline job using this reservation will execute with the
  /// slot capacity specified in the slot_capacity field at most.
  public var ignoreIdleSlots: Swift.Bool = Swift.Bool()

  /// Optional. The configuration parameters for the auto scaling feature.
  public var autoscale: Reservation.Autoscale? = nil

  /// Optional. Job concurrency target which sets a soft upper bound on the
  /// number of jobs that can run concurrently in this reservation. This is a
  /// soft target due to asynchronous nature of the system and various
  /// optimizations for small queries. Default value is 0 which means that
  /// concurrency target will be automatically computed by the system. NOTE: this
  /// field is exposed as target job concurrency in the Information Schema, DDL
  /// and BigQuery CLI.
  public var concurrency: Swift.Int64 = Swift.Int64()

  /// Output only. Creation time of the reservation.
  public var creationTime: GoogleWKT.Timestamp? = nil

  /// Output only. Last update time of the reservation.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Applicable only for reservations located within one of the BigQuery
  /// multi-regions (US or EU).
  ///
  /// If set to true, this reservation is placed in the organization's
  /// secondary region which is designated for disaster recovery purposes.
  /// If false, this reservation is placed in the organization's default region.
  ///
  /// NOTE: this is a preview feature. Project must be allow-listed in order to
  /// set this field.
  @available(*, deprecated)
  public var multiRegionAuxiliary: Swift.Bool = Swift.Bool()

  /// Optional. Edition of the reservation.
  public var edition: Edition = Edition()

  /// Output only. The current location of the reservation's primary replica.
  /// This field is only set for reservations using the managed disaster recovery
  /// feature.
  public var primaryLocation: Swift.String = Swift.String()

  /// Optional. The current location of the reservation's secondary replica. This
  /// field is only set for reservations using the managed disaster recovery
  /// feature. Users can set this in create reservation calls
  /// to create a failover reservation or in update reservation calls to convert
  /// a non-failover reservation to a failover reservation(or vice versa).
  public var secondaryLocation: Swift.String = Swift.String()

  /// Output only. The location where the reservation was originally created.
  /// This is set only during the failover reservation's creation. All billing
  /// charges for the failover reservation will be applied to this location.
  public var originalPrimaryLocation: Swift.String = Swift.String()

  /// Optional. The overall max slots for the reservation, covering slot_capacity
  /// (baseline), idle slots (if ignore_idle_slots is false) and scaled slots.
  /// If present, the reservation won't use more than the specified number of
  /// slots, even if there is demand and supply (from idle slots).
  /// NOTE: capping a reservation's idle slot usage is best effort and its
  /// usage may exceed the max_slots value. However, in terms of
  /// autoscale.current_slots (which accounts for the additional added slots), it
  /// will never exceed the max_slots - baseline.
  ///
  ///
  /// This field must be set together with the scaling_mode enum value,
  /// otherwise the request will be rejected with error code
  /// `google.rpc.Code.INVALID_ARGUMENT`.
  ///
  /// If the max_slots and scaling_mode are set, the autoscale or
  /// autoscale.max_slots field must be unset. Otherwise the request will be
  /// rejected with error code `google.rpc.Code.INVALID_ARGUMENT`. However, the
  /// autoscale field may still be in the output. The autopscale.max_slots will
  /// always show as 0 and the autoscaler.current_slots will represent the
  /// current slots from autoscaler excluding idle slots.
  /// For example, if the max_slots is 1000 and scaling_mode is AUTOSCALE_ONLY,
  /// then in the output, the autoscaler.max_slots will be 0 and the
  /// autoscaler.current_slots may be any value between 0 and 1000.
  ///
  /// If the max_slots is 1000, scaling_mode is ALL_SLOTS, the baseline is 100
  /// and idle slots usage is 200, then in the output, the autoscaler.max_slots
  /// will be 0 and the autoscaler.current_slots will not be higher than 700.
  ///
  /// If the max_slots is 1000, scaling_mode is IDLE_SLOTS_ONLY, then in the
  /// output, the autoscaler field will be null.
  ///
  /// If the max_slots and scaling_mode are set, then the ignore_idle_slots field
  /// must be aligned with the scaling_mode enum value.(See details in
  /// ScalingMode comments). Otherwise the request will be rejected with
  /// error code `google.rpc.Code.INVALID_ARGUMENT`.
  ///
  /// Please note,  the max_slots is for user to manage the part of slots greater
  /// than the baseline. Therefore, we don't allow users to set max_slots smaller
  /// or equal to the baseline as it will not be meaningful. If the field is
  /// present and slot_capacity>=max_slots, requests will be rejected with error
  /// code `google.rpc.Code.INVALID_ARGUMENT`.
  ///
  /// Please note that if max_slots is set to 0, we will treat it as unset.
  /// Customers can set max_slots to 0 and set scaling_mode to
  /// SCALING_MODE_UNSPECIFIED to disable the max_slots feature.
  public var maxSlots: Swift.Int64? = nil

  /// Optional. The scaling mode for the reservation.
  /// If the field is present but max_slots is not present, requests will be
  /// rejected with error code `google.rpc.Code.INVALID_ARGUMENT`.
  public var scalingMode: Reservation.ScalingMode = Reservation.ScalingMode()

  /// Optional. The labels associated with this reservation. You can use these
  /// to organize and group your reservations.
  /// You can set this property when you create or update a reservation.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The reservation group that this reservation belongs to.
  /// You can set this property when you create or update a reservation.
  /// Reservations do not need to belong to a reservation group.
  /// Format:
  /// projects/{project}/locations/{location}/reservationGroups/{reservation_group}
  /// or just {reservation_group}
  public var reservationGroup: Swift.String = Swift.String()

  /// Output only. The Disaster Recovery(DR) replication status of the
  /// reservation. This is only available for the primary replicas of DR/failover
  /// reservations and provides information about the both the staleness of the
  /// secondary and the last error encountered while trying to replicate changes
  /// from the primary to the secondary. If this field is blank, it means that
  /// the reservation is either not a DR reservation or the reservation is a DR
  /// secondary or that any replication operations on the reservation have
  /// succeeded.
  public var replicationStatus: Reservation.ReplicationStatus? = nil

  /// Optional. The scheduling policy to use for jobs and queries running under
  /// this reservation. The scheduling policy controls how the reservation's
  /// resources are distributed.
  ///
  /// This feature is not yet generally available.
  public var schedulingPolicy: SchedulingPolicy? = nil

  /// Output only. The reservation group path of the reservation from root to
  /// leaf. The order of elements matters: the first element is the top level
  /// group and the last element is the direct parent reservation group. For
  /// example, if a reservation is under group-1 -> group-2 -> group-3, then the
  /// reservation group path is ["group-1", "group-2", "group-3"].
  public var reservationGroupPath: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Reservation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Reservation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let slotCapacity = CodingKeys(stringValue: "slotCapacity")
    static let ignoreIdleSlots = CodingKeys(stringValue: "ignoreIdleSlots")
    static let autoscale = CodingKeys(stringValue: "autoscale")
    static let concurrency = CodingKeys(stringValue: "concurrency")
    static let creationTime = CodingKeys(stringValue: "creationTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let multiRegionAuxiliary = CodingKeys(stringValue: "multiRegionAuxiliary")
    static let edition = CodingKeys(stringValue: "edition")
    static let primaryLocation = CodingKeys(stringValue: "primaryLocation")
    static let secondaryLocation = CodingKeys(stringValue: "secondaryLocation")
    static let originalPrimaryLocation = CodingKeys(stringValue: "originalPrimaryLocation")
    static let maxSlots = CodingKeys(stringValue: "maxSlots")
    static let scalingMode = CodingKeys(stringValue: "scalingMode")
    static let labels = CodingKeys(stringValue: "labels")
    static let reservationGroup = CodingKeys(stringValue: "reservationGroup")
    static let replicationStatus = CodingKeys(stringValue: "replicationStatus")
    static let schedulingPolicy = CodingKeys(stringValue: "schedulingPolicy")
    static let reservationGroupPath = CodingKeys(stringValue: "reservationGroupPath")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "slotCapacity",
      "ignoreIdleSlots",
      "autoscale",
      "concurrency",
      "creationTime",
      "updateTime",
      "multiRegionAuxiliary",
      "edition",
      "primaryLocation",
      "secondaryLocation",
      "originalPrimaryLocation",
      "maxSlots",
      "scalingMode",
      "labels",
      "reservationGroup",
      "replicationStatus",
      "schedulingPolicy",
      "reservationGroupPath",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .slotCapacity) {
      self.slotCapacity = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ignoreIdleSlots) {
      self.ignoreIdleSlots = value
    }
    self.autoscale = try container.decodeIfPresent(Reservation.Autoscale.self, forKey: .autoscale)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .concurrency) {
      self.concurrency = value
    }
    self.creationTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .creationTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .multiRegionAuxiliary) {
      self.multiRegionAuxiliary = value
    }
    if let value = try container.decodeIfPresent(Edition.self, forKey: .edition) {
      self.edition = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryLocation) {
      self.primaryLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryLocation) {
      self.secondaryLocation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .originalPrimaryLocation)
    {
      self.originalPrimaryLocation = value
    }
    self.maxSlots = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxSlots)
    if let value = try container.decodeIfPresent(Reservation.ScalingMode.self, forKey: .scalingMode)
    {
      self.scalingMode = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservationGroup) {
      self.reservationGroup = value
    }
    self.replicationStatus = try container.decodeIfPresent(
      Reservation.ReplicationStatus.self, forKey: .replicationStatus)
    self.schedulingPolicy = try container.decodeIfPresent(
      SchedulingPolicy.self, forKey: .schedulingPolicy)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .reservationGroupPath)
    {
      self.reservationGroupPath = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.slotCapacity, forKey: .slotCapacity)
    try container.encode(self.ignoreIdleSlots, forKey: .ignoreIdleSlots)
    try container.encodeIfPresent(self.autoscale, forKey: .autoscale)
    try container.encode(self.concurrency, forKey: .concurrency)
    try container.encodeIfPresent(self.creationTime, forKey: .creationTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.multiRegionAuxiliary, forKey: .multiRegionAuxiliary)
    try container.encode(self.edition, forKey: .edition)
    try container.encode(self.primaryLocation, forKey: .primaryLocation)
    try container.encode(self.secondaryLocation, forKey: .secondaryLocation)
    try container.encode(self.originalPrimaryLocation, forKey: .originalPrimaryLocation)
    try container.encodeIfPresent(self.maxSlots, forKey: .maxSlots)
    try container.encode(self.scalingMode, forKey: .scalingMode)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.reservationGroup, forKey: .reservationGroup)
    try container.encodeIfPresent(self.replicationStatus, forKey: .replicationStatus)
    try container.encodeIfPresent(self.schedulingPolicy, forKey: .schedulingPolicy)
    try container.encode(self.reservationGroupPath, forKey: .reservationGroupPath)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Auto scaling settings.
  public struct Autoscale: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The slot capacity added to this reservation when autoscale
    /// happens. Will be between [0, max_slots]. Note: after users reduce
    /// max_slots, it may take a while before it can be propagated, so
    /// current_slots may stay in the original value and could be larger than
    /// max_slots for that brief period (less than one minute)
    public var currentSlots: Swift.Int64 = Swift.Int64()

    /// Optional. Number of slots to be scaled when needed.
    public var maxSlots: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Autoscale`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Autoscale().with { $0.currentSlots = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let currentSlots = CodingKeys(stringValue: "currentSlots")
      static let maxSlots = CodingKeys(stringValue: "maxSlots")

      static let _knownKeys: Set<Swift.String> = [
        "currentSlots",
        "maxSlots",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .currentSlots) {
        self.currentSlots = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxSlots) {
        self.maxSlots = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.currentSlots, forKey: .currentSlots)
      try container.encode(self.maxSlots, forKey: .maxSlots)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.reservation.v1.Reservation.Autoscale"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Disaster Recovery(DR) replication status of the reservation.
  public struct ReplicationStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The last error encountered while trying to replicate changes
    /// from the primary to the secondary. This field is only available if the
    /// replication has not succeeded since.
    public var error: GoogleRpc.Status? = nil

    /// Output only. The time at which the last error was encountered while
    /// trying to replicate changes from the primary to the secondary. This field
    /// is only available if the replication has not succeeded since.
    public var lastErrorTime: GoogleWKT.Timestamp? = nil

    /// Output only. A timestamp corresponding to the last change on the primary
    /// that was successfully replicated to the secondary.
    public var lastReplicationTime: GoogleWKT.Timestamp? = nil

    /// Output only. The time at which a soft failover for the reservation and
    /// its associated datasets was initiated. After this field is set, all
    /// subsequent changes to the reservation will be rejected unless a hard
    /// failover overrides this operation. This field will be cleared once the
    /// failover is complete.
    public var softFailoverStartTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReplicationStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReplicationStatus().with { $0.error = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let error = CodingKeys(stringValue: "error")
      static let lastErrorTime = CodingKeys(stringValue: "lastErrorTime")
      static let lastReplicationTime = CodingKeys(stringValue: "lastReplicationTime")
      static let softFailoverStartTime = CodingKeys(stringValue: "softFailoverStartTime")

      static let _knownKeys: Set<Swift.String> = [
        "error",
        "lastErrorTime",
        "lastReplicationTime",
        "softFailoverStartTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      self.lastErrorTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .lastErrorTime)
      self.lastReplicationTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .lastReplicationTime)
      self.softFailoverStartTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .softFailoverStartTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.error, forKey: .error)
      try container.encodeIfPresent(self.lastErrorTime, forKey: .lastErrorTime)
      try container.encodeIfPresent(self.lastReplicationTime, forKey: .lastReplicationTime)
      try container.encodeIfPresent(self.softFailoverStartTime, forKey: .softFailoverStartTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.reservation.v1.Reservation.ReplicationStatus"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The scaling mode for the reservation. This enum determines how the
  /// reservation scales up and down.
  public enum ScalingMode: Codable, Equatable, Sendable {
    /// Default value of ScalingMode.
    case unspecified
    /// The reservation will scale up only using slots from autoscaling. It will
    /// not use any idle slots even if there may be some available. The upper
    /// limit that autoscaling can scale up to will be max_slots - baseline.
    /// For example, if max_slots is 1000, baseline is 200 and customer sets
    /// ScalingMode to AUTOSCALE_ONLY, then autoscalerg will scale up to 800
    /// slots and no idle slots will be used.
    ///
    /// Please note, in this mode, the ignore_idle_slots field must be set to
    /// true. Otherwise the request will be rejected with error code
    /// `google.rpc.Code.INVALID_ARGUMENT`.
    case autoscaleOnly
    /// The reservation will scale up using only idle slots contributed by
    /// other reservations or from unassigned commitments. If no idle slots are
    /// available it will not scale up further. If the idle slots which it is
    /// using are reclaimed by the contributing reservation(s) it may be forced
    /// to scale down. The max idle slots the reservation can be max_slots -
    /// baseline capacity. For example, if max_slots is 1000, baseline is 200 and
    /// customer sets ScalingMode to IDLE_SLOTS_ONLY,
    /// 1. if there are 1000 idle slots available in other reservations, the
    /// reservation will scale up to 1000 slots with 200 baseline and 800 idle
    /// slots.
    /// 2. if there are 500 idle slots available in other reservations, the
    /// reservation will scale up to 700 slots with 200 baseline and 500 idle
    /// slots.
    /// Please note, in this mode, the reservation might not be able to scale up
    /// to max_slots.
    ///
    /// Please note, in this mode, the ignore_idle_slots field must be set to
    /// false. Otherwise the request will be rejected with error code
    /// `google.rpc.Code.INVALID_ARGUMENT`.
    case idleSlotsOnly
    /// The reservation will scale up using all slots available to it. It will
    /// use idle slots contributed by other reservations or from unassigned
    /// commitments first. If no idle slots are available it will scale up using
    /// autoscaling. For example, if max_slots is 1000, baseline is 200 and
    /// customer sets ScalingMode to ALL_SLOTS,
    /// 1. if there are 800 idle slots available in other reservations, the
    /// reservation will scale up to 1000 slots with 200 baseline and 800 idle
    /// slots.
    /// 2. if there are 500 idle slots available in other reservations, the
    /// reservation will scale up to 1000 slots with 200 baseline, 500 idle
    /// slots and 300 autoscaling slots.
    /// 3. if there are no idle slots available in other reservations, it will
    /// scale up to 1000 slots with 200 baseline and 800 autoscaling slots.
    ///
    /// Please note, in this mode, the ignore_idle_slots field must be set to
    /// false. Otherwise the request will be rejected with error code
    /// `google.rpc.Code.INVALID_ARGUMENT`.
    case allSlots
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .autoscaleOnly: return 1
      case .idleSlotsOnly: return 2
      case .allSlots: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SCALING_MODE_UNSPECIFIED"
      case .autoscaleOnly: return "AUTOSCALE_ONLY"
      case .idleSlotsOnly: return "IDLE_SLOTS_ONLY"
      case .allSlots: return "ALL_SLOTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ScalingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SCALING_MODE_UNSPECIFIED": self = .unspecified
      case "AUTOSCALE_ONLY": self = .autoscaleOnly
      case "IDLE_SLOTS_ONLY": self = .idleSlotsOnly
      case "ALL_SLOTS": self = .allSlots
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ScalingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .autoscaleOnly
      case 2: self = .idleSlotsOnly
      case 3: self = .allSlots
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SCALING_MODE_UNSPECIFIED")
      case .autoscaleOnly: return try container.encode("AUTOSCALE_ONLY")
      case .idleSlotsOnly: return try container.encode("IDLE_SLOTS_ONLY")
      case .allSlots: return try container.encode("ALL_SLOTS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.Reservation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
