// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The scheduling policy controls how a reservation's resources are distributed.
public struct SchedulingPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. If present and > 0, the reservation will attempt to limit the
  /// concurrency of jobs running for any particular project within it to the
  /// given value.
  ///
  /// This feature is not yet generally available.
  public var concurrency: Swift.Int64? = nil

  /// Optional. If present and > 0, the reservation will attempt to limit the
  /// slot consumption of queries running for any particular project within it to
  /// the given value.
  ///
  /// This feature is not yet generally available.
  public var maxSlots: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SchedulingPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchedulingPolicy().with { $0.concurrency = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let concurrency = CodingKeys(stringValue: "concurrency")
    static let maxSlots = CodingKeys(stringValue: "maxSlots")

    static let _knownKeys: Set<Swift.String> = [
      "concurrency",
      "maxSlots",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.concurrency = try container.decodeIfPresent(Swift.Int64.self, forKey: .concurrency)
    self.maxSlots = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxSlots)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.concurrency, forKey: .concurrency)
    try container.encodeIfPresent(self.maxSlots, forKey: .maxSlots)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.SchedulingPolicy"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
